name: CML Model Test

on:
  push:
    branches: [dev-branch]
  pull_request:
    branches: [dev-branch]

jobs:
  model-test:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/test_key.json

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up GCP credentials
      run: echo "${{ secrets.GCP_KEY_JSON }}" > $GOOGLE_APPLICATION_CREDENTIALS

    - name: Run model test
      run: python test_model.py

    - name: Post CML report
      uses: iterative/setup-cml@v2.0.1
      with:
        markdown: report.md
